[tool.poetry]
name = "reqman"
version = "0.0.0"  
description = "Create your http(s)-tests in simple yaml files, and run them with command line, against various environments"
authors = ["manatlan <manatlan@gmail.com>"]
repository = "https://github.com/manatlan/reqman"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
aiohttp = "*"
py-dom-xpath-six = "*"
pyyaml = ">=4.2b1"
stpl = ">=1.13.2"
colorama = "*"
pyjwt = "*"
junit-xml = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-asyncio = "*"

[tool.poetry.scripts]
reqman = "reqman:main"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
py = "^1.11.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
