# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Windows EXE

on:
  workflow_dispatch:   # déclenchement manuel possible

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # adapte si nécessaire

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install UPX
        run: |
          curl -L -o upx.zip https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-win64.zip
          tar -xf upx.zip
          echo "${{ github.workspace }}\upx-4.2.4-win64" >> $env:GITHUB_PATH


      - name: Install dependencies
        run: |
          uv sync --dev
          uv build

      - name: Build EXE with pyinstaller
        run: uv run buildWinExe.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: reqman-windows-exe
          path: dist/*.exe
