name: "On Tag -> Deploy a release to pypi"
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: init
        run: |
          uv sync
          uv sync --dev

      - name: Test with pytest
        run: uv run pytest

      - name: Patch Sources with "tag version ref"
        run: |
          python .github/workflows/update_version.py ${{github.ref_name}}

      - name: Build project
        run: uv build -o dist/

      - name: del garbage
        run: rm dist/readme.md

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}