name: "On Tag -> Deploy a release to pypi"
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Patch Sources with "tag version ref"
        run: python .github/workflows/update_version.py "v1.0.0"
        # run: python .github/workflows/update_version.py ${{github.ref_name}}

      - name: Install pytest + dependancies
        run: |
            python -m pip install -U pip poetry
            poetry install --with dev

      - name: Test with pytest
        run: |
            poetry run pytest

      #- name: Build and publish to pypi
      #  uses: JRubics/poetry-publish@v1.12
        #with:
        #  pypi_token: ${{ secrets.PYPI_TOKEN }}